USE UNIVERSITYDATABASE11

-- SELF RERENCING KEYS :  SUCH TABLES THAT HAS FOREIGN KEY DEFINED ON THE CANDIDATE KEY OF SAME TABLE.
-- CANDIDATE KEY MEANS A PRIMARY KEY OR A UNIQUE KEY.

CREATE TABLE ccc
(
EmpID int,
EmpName varchar(30),
EmpManagerID int
)

-- REQUIREMENT :  HOW TO ENSURE THAT EVERY MANAGER IS A VALID EMPLOYEE IN ABOVE TABLE?
-- SOLUTION : WE NEED TO RELATE THE MANAGERID COLUMN WITH EMPLOYEEID COLUMN OF EMPLOYEE TABLE

-- STEP 1: ADD PRIMARY KEY TO EXISTING TABLE?
ALTER TABLE empDetails ALTER COLUMN EmpID INT NOT NULL 
ALTER TABLE empDetails ADD CONSTRAINT PK_EMP_ID PRIMARY KEY(EmpID)

-- STEP 2: ADD FOREIGN KEY TO EXISTING TABLE?
ALTER TABLE empDetails ADD CONSTRAINT FK_EMP_ID FOREIGN KEY(EmpManagerID) REFERENCES empDetails(EmpID)

-- DATA INSERT
INSERT INTO empDetails VALUES (1001, 'JOHN', 1001)
INSERT INTO empDetails VALUES (1002, 'JEFF', 1001)
INSERT INTO empDetails VALUES (1003, 'SAM', 9999)			-- ERROR. INVALID MANAGER ID.  9999 IS NOT A VALID EMPLOYEE ID
INSERT INTO empDetails VALUES (1004, 'AMIN', 1002)			-- EXECUTION CONTINUES. THIS ROW IS INSERTED.

-- TO VERIFY THE RESULT:
SELECT * FROM empDetails

-- WHAT IF YOU WANTED TO STOP THE EXECUTION AT POINT OF FAILURE IN A BATCH?
SET XACT_ABORT ON				-- STOP THE BATCH EXECUTION EXACTLY AT THE SAME PLACE WHERE YOU HAVE 1ST ERROR. SESSION LEVEL.
INSERT INTO empDetails VALUES (2001, 'JOHN', 2001)
INSERT INTO empDetails VALUES (2002, 'JEFF', 2001)
INSERT INTO empDetails VALUES (2003, 'SAM', 9999)			-- ERROR. INVALID MANAGER ID.  9999 IS NOT A VALID EMPLOYEE ID
INSERT INTO empDetails VALUES (2004, 'AMIN', 2002)			-- THIS INSERT SHOULD NOT BE EXECUTED.

-- TO VERIFY THE RESULT:
SELECT * FROM empDetails

INSERT INTO empDetails VALUES (2004, 'AMIN', 2002)


SET XACT_ABORT OFF


/*
INDEX		:	AN ADDITIONAL DATA STRUCTURE DEFINED ON TABLES 
				USED FOR FASTER SEARCH OPERATIONS BY AUTO SORTING THE DATA AT DATABASE FILE LEVEL.
				THESE INDEXES REQUIRE ADDITIONAL SPACE FOR STORING THIS "PRE-SORTED" DATA.

				CASE 1:		INDEXES ARE AUTO CREATED WHENEVER WE DEFINE PRIMARY KEY & / UNIQUE KEY ON TABLE

				CASE 2:		FOR COLUMNS ON WHICH THERE IS NO PRIMARY KEY NOR UNIQUE KEY, WE CAN DEFINE INDEXES.
							PURPOSE:	FASTER SEARCH OPERATIONS  [EXAMPLE : WHERE CONDITIONS]

				BASIC TYPES OF INDEXES:
					1. CLUSTERED INDEX		:	THIS INDEX CONTROLS, CARES THE ACTUAL TABLE
												MEANS, THE INDEX DATA IS "CLUSTERED" OR "GROUPED" WITH TABLE
												THERE CAN BE ONLY ONE CLUSTERED INDEX PER TABLE.
												WHENEVER WE DEFINE PRIMARY KEY, ONE CLUSTERED INDEX IS AUTO CREATED.
												IN THIS CASE, WE CANNOT CREATE ADDITIONAL CLUSTERED INDEXES ON TABLE
						
					2. NON CLUSTERED INDEX	:	THE INDEX REFERENCES OR DIRECTS THE QUERY TO THE TABLE DATA.
												THERE CAN BE UPTO 999 NONCLUSTERED INDEXES PER TABLE.
												WHENEVER WE DEFINE UNIQUE KEY, ONE NONCLUSTERED INDEX IS AUTO CREATED.
												++ WE CAN ALSO DEFINED OUT OWN NEW, NONCLUSTERED INDEXES

				SYNTAX :	
				CREATE CLUSTERED  | NONCLUSTERED  INDEX <INDEXNAME>  ON  <TABLE-NAME> (<<COLUMNNAME>> ASC | DESC)
*/


CREATE TABLE EMPLOYEE_INFO			
(
EMP_ID  INT,				
EMP_FNAME VARCHAR (30),		
EMP_LNAME VARCHAR (40),		
EMP_CNTRY CHAR(50),			 
EMP_SAL  BIGINT				
)						

ALTER TABLE EMPLOYEE_INFO ADD CONSTRAINT UQ_EMP_ID UNIQUE(EMP_ID)



INSERT INTO  EMPLOYEE_INFO VALUES (1001, 'AMIN', 'A', 'CANADA', 45678)	 
INSERT   EMPLOYEE_INFO VALUES	('1002', 'JOHN', 'A', 'CANADA', 643643),
								(1003, 'SAI', 'H', 'INDIA', 36363),
								(1004, 'SAISHA', 'T', 'INDIA', NULL), 
								(1005, 'SAISH', 'G', 'INDIA', 43643)
INSERT   EMPLOYEE_INFO VALUES (1006, 'ADAM', 'H', 'USA', NULL) 



SELECT * FROM EMPLOYEE_INFO			-- AN INTERNAL PART OF SQL SERVER ARCHITECTURE "QUERY OPTIMIZER" WILL CHECK FOR BEST WAY 
									-- TO EXECUTE THE QUERIES BASED ON AVAILABLE INDEXES ON THE TABLE.


CREATE CLUSTERED    INDEX IND2  ON  EMPLOYEE_INFO (EMP_ID DESC)
CREATE NONCLUSTERED INDEX IND3  ON  EMPLOYEE_INFO (EMP_SAL ASC)

SELECT * FROM EMPLOYEE_INFO	


-- COMPOSITE INDEX:	AN INDEX DEFINED ON MORE THAN ONE COLUMN
ALTER TABLE EMPLOYEE_INFO ADD CONSTRAINT UQ_EMP_ID2 UNIQUE(EMP_FNAME,EMP_SAL)


/*
THANK YOU PARTICIPANT WHO HAVE BEEN RESPONSIVE TO MY QUESTIONS SINCE OUR START OF THE CLASS.
NOW, FEW MORE QUESTIONS FOR YOUR BETTER UNDERSTANDING AND RECHECK OF YOUR LEARNING SKILLS

	1. WHY AN INDEX IS REALLY REQUIRED WHEN WORKING WITH PRIMARY KEY OR UNIQUE KEY ?

	2. PRIMARY KEY IS NOT DEFINED ON A TABLE DURING CRATION BUT ADDED LATER. IN THIS CASE, WILL INDEX GET
	   CREATED AUTOMATICALLY OR NOT?	

	3. CAN A SINGLE KEY HAVE MORE THAN ONE COLUMN ?

	4. CAN A SINGLE TABLE HAVE MORE THAN ONE COLUMN IN A PRIMARY KEY ? 

	5. WHAT ARE THE PRE-REQUISITES FOR DEFINING A FOREIGN KEY ?

	6. YOU WERE GIVEN A BANK DATABASE WITH TWO RELATED TABLES:
				ACCOUNTS TABLE		:	100m ROWS;	PRIMARY KEY
				CUSTOMERS TABLE		:	90m ROWS :  UNIQUE KEY
		RELATION : ACCOUNTS TABLE RELATED TO CUSTOMERS TABLE. MEANS, EVERY ACCOUNT IS OWNED BY A VALID CUSTOMER.

		TASK : HOW TO ENSURE FASTER INSERTIONS OF DATA INTO ACCOUNTS TABLE ? 






























-- EXAMPLE FOR MERGE JOIN:  HOW TO REPORT LIST OF ALL MANAGERS WITH THEIR EMPLOYEES ?
SELECT * FROM empDetails AS E1
INNER JOIN						
empDetails AS E2
ON
E1.EmpID = E2.EmpManagerID


SELECT E1.EmpID AS MANAGER_ID, E1.EmpName AS MANAGER_NAME, E2.EmpID AS EMPLOYEE_ID, E2.EmpName AS EMPLOYEE_NAME
FROM empDetails AS E1
INNER JOIN						
empDetails AS E2
ON
E1.EmpID = E2.EmpManagerID


-- TASK 1 : HOW TO REPORT LIST OF ALL EMPLOYEES AND THEIR RESPECTIVE MANAGERS?
-- TASK 2 : HOW TO REPORT LIST OF ALL EMPLOYEES WHOSE MANAGER IS JOHN?
-- TASK 3 : REPORT ALL EMPLOYEES FOR EACH MANAGER ?
