/*
SCHEMAS  : DATABASE OBJECTS USED TO GROUP MULTIPLE TABLES OR VIEWS, PROCEDURES, ETC..]
PURPOSE  : USED FOR EASY DATA ACCESS AND EASY SECURITY MANAGEMENT
DEFAULT SCHEMA IS "DBO". MEANS: " DATABASE OWNER "
*/

-- ITEM #1. HOW TO CREATE SCHEMAS IN A DATABASE ?
CREATE SCHEMA SCHEMA1
GO
CREATE SCHEMA SCHEMA2

-- ITEM #2. HOW TO CREATE THE TABLES USING THE SCHEMAS ?
CREATE TABLE SCHEMA1.TABLE1 (COL1 INT, COL2 INT, COL3 DATE)
GO
CREATE TABLE SCHEMA1.TABLE2 (COL1 INT, COL2 INT)

-- ITEM #3: HOW TO STORE DATA INTO THE ABOVE TABLES ?
INSERT INTO SCHEMA1.TABLE1 VALUES (1,1, '2018-12-31'), (2,2,GETDATE()), (3,3,'2018/12/31')

-- ITEM #4: HOW TO REPORT DATA FROM ABOVE TABLES ?
SELECT * FROM SCHEMA1.TABLE1

-- ITEM #5: HOW TO MOVE A TABLE FROM ONE SCHEMA TO ANOTHER ?
ALTER SCHEMA SCHEMA2 TRANSFER SCHEMA1.TABLE1

-- ITEM #6: HOW TO TEST THE ABOVE TABLE TRANSFER ?
SELECT * FROM SCHEMA2.TABLE1 



-- WHILE CREATING TABLE, IF WE DO NOT SPECIFY ANY SCHEMA THEN DEFAULT SCHEMA IS dbo
-- IF A TABLE BELONGS TO dbo SCHEMA THEN INCLUDING THE SCHEMA NAME IS OPTIONAL.


CREATE TABLE TABLE1 (COL1 INT, COL2 INT, COL3 DATE)
GO
CREATE TABLE TABLE2 (COL1 INT, COL2 INT)

INSERT INTO TABLE1 VALUES (1,1, '2018-12-31'), (2,2,GETDATE()), (3,3,'2018/12/31')
INSERT INTO DBO.TABLE2 VALUES (1,1, '2018-12-31'), (2,2,GETDATE()), (3,3,'2018/12/31')

SELECT * FROM TABLE1 
SELECT * FROM DBO.TABLE2









/*
TASK FOR DEVELOPERS:	 YOU HAVE A TABLE DESIGN REQUIREMENT AT https://sqlschool.com/RTCS_SQL1.html
						 YOU SHALL DESIGN A DATABASE
						 DEFINE SCHEMAS
						 DEFINE TABLES
						 ADD RELATIONS
						 INSERT GIVEN SAMPLE DATA
						 MAIL ME YOUR .SQL FILE SOLUTION


TASKS FOR SQL DBAs:
						1.  FROM TODAY'S EXAMPLE IF YOU NEED TO MIGRATE OR MOVE STUDENTS TABLE THEN WHAT SHOULD
							BE YOUR PRECAUTIONARY MEASURES?

						2.	FROM TODAY'S EXAMPLE IF YOU NEED TO SECURELY GIVE ACCESS TO STUDENTS TABLE AND STAFF TABLE
							TO VARIOUS END USERS IN THE UNIVERSITY THEN WHAT WOULD BE YOUR RECOMMENDATIONS FOR DESIGN?

						3. IF DATA PAGES IN THE COURSES TABLE ARE CORRUPTED THEN HOW IT WILL IMPACT THE DEVELOPERS?
*/







SELECT * FROM #TABLE1			-- ERROR. REASON : THIS IS A LOCAL TEMPORARY TABLE. ONLY AT SESSION LEVEL. 
SELECT * FROM ##TABLE2			--- THIS IS A GLOBAL TEMPORARY TABLE. ACCESSIBLE ACROSS SESSIONS. NO ERROR