CREATE DATABASE OnlineReservationsDB

use OnlineReservationsDB

CREATE TABLE RESERVATIONS
(
CRAFT_CODE VARCHAR(30),
NO_OF_SEATS INT,
CLASS VARCHAR(30)
)
GO

CREATE TABLE FLIGHT
(
CRAFT_CODE VARCHAR(30),
SOURCE VARCHAR(30),
DESTINATION VARCHAR(30)
)


CREATE VIEW VW_FLIGHT_RESERVATIONS
AS
SELECT R.CRAFT_CODE,R.NO_OF_SEATS,R.CLASS,
F.SOURCE,F.DESTINATION FROM RESERVATIONS  AS R
JOIN
FLIGHT  AS F
ON
R.CRAFT_CODE = F.CRAFT_CODE


-- NOW, WE NEED TO INSERT DATA INTO THE BASE TABLE USING ABOVE VIEW?
INSERT INTO VW_FLIGHT_RESERVATIONS VALUES ('AI01', 11, 'ECO', 'CITY1', 'CITY2') -- ERROR

SELECT * FROM VW_FLIGHT_RESERVATIONS

-- SOLUTION TO ABOVE ERROR:
CREATE TRIGGER trigVwInserts 
ON VW_FLIGHT_RESERVATIONS
INSTEAD OF INSERT
AS
	BEGIN
	DECLARE @CODE VARCHAR(30), @SEATS INT, @CLASS VARCHAR(30) , @SRC VARCHAR(30) , @DEST VARCHAR(30) 

	-- ASSIGN VALUES TO ABOVE VARIABLES
	SELECT @CODE = CRAFT_CODE FROM INSERTED 
	SELECT @SEATS = NO_OF_SEATS FROM INSERTED 
	SELECT @CLASS = CLASS FROM INSERTED 
	SELECT @SRC = SOURCE  FROM INSERTED 
	SELECT @DEST = DESTINATION FROM INSERTED 

	-- DISTRIBUTE THE DATA TO ACTUAL BASE TABLES
	INSERT INTO Reservations VALUES (@CODE, @SEATS, @CLASS) 
	INSERT INTO FLIGHT VALUES (@CODE, @SRC, @DEST) 
	END  


-- HOW TO TEST ABOVE VIEW?
INSERT INTO VW_FLIGHT_RESERVATIONS VALUES ('AI01', 11, 'ECO', 'CITY1', 'CITY2') 
INSERT INTO VW_FLIGHT_RESERVATIONS VALUES ('AI02', 22, 'ECO', 'CITY11', 'CITY22')

SELECT * FROM Reservations
SELECT * FROM FLIGHT 


ALTER TRIGGER trigVwInserts 
ON VW_FLIGHT_RESERVATIONS
INSTEAD OF INSERT
AS
	BEGIN
	BEGIN TRANSACTION				
	BEGIN TRY
	DECLARE @CODE VARCHAR(30), @SEATS INT, @CLASS VARCHAR(30) , @SRC VARCHAR(30) , @DEST VARCHAR(30) 
	-- ASSIGN VALUES TO ABOVE VARIABLES
	SELECT @CODE = CRAFT_CODE FROM INSERTED 
	SELECT @SEATS = NO_OF_SEATS FROM INSERTED 
	SELECT @CLASS = CLASS FROM INSERTED 
	SELECT @SRC = SOURCE  FROM INSERTED 
	SELECT @DEST = DESTINATION FROM INSERTED 
	-- DISTRIBUTE THE DATA TO ACTUAL BASE TABLES
	INSERT INTO Reservations VALUES (@CODE, @SEATS, @CLASS) 
	INSERT INTO FLIGHT VALUES (@CODE, @SRC, @DEST) 
	COMMIT
	END  TRY
	BEGIN CATCH
	PRINT 'ERROR DURING TRIGGER EXECUTION'
	ROLLBACK
	END CATCH
	END



	-- DEFINE A STORED PROCEDURE AND ENSURE DYNAMIC INSERTS INTO VIEW. THE VIEW DISTRIBUTES DATA TO MULTIPLE BASE TABLES
	-- USING TRIGGERS IN A TRANSACTIONAL ENVIRONMENT

	CREATE PROC USP_VALIDATE_INSERT (@CODE CHAR(4), @SEATS TINYINT, @CLASS CHAR(3), @SRC VARCHAR(10), @DEST VARCHAR(10))
	AS
		BEGIN
		IF @SRC != @DEST  AND @SEATS <= 10 
			INSERT INTO VW_FLIGHT_RESERVATIONS VALUES (@CODE, @SEATS, @CLASS, @SRC, @DEST) 
		ELSE
			PRINT 'INVALID RESERVATION'
		END 


-- HOW TO EXECUTE ABOVE SP?
EXEC USP_VALIDATE_INSERT 'AI09', 9, 'ECO', 'HYB', 'NYC'

-- PROCEDURE  >> VIEW >> TRIGGER >> MAJIC TABLES > BASE TABLES

-- VERIFY:
SELECT * FROM Reservations
SELECT * FROM FLIGHT 



-- SQL INJECTION ATTACK : A PHENOMENA IN WHICH END USERS MAY HAVE OPTION TO INPUT UNWANTED, INCORRECT PARAMETER VALUES.
EXEC USP_VALIDATE_INSERT	@CODE  = 'AI01;DROP PROCEDURE USP_VALIDATE_INSERT'


-- SOLUTION FOR SQL INJECTION ATTACKS :  ENSURE TO SPECIFY CORRECT PARAMETER TYPE AND CORRECT LENGTH




