-- drop table tbltest

use tempdb 
go

CREATE TABLE tbltest
(
ID INT,
Value INT,
RANK INT
)

INSERT INTO tbltest VALUES(1,11,NULL)	INSERT INTO tbltest VALUES(2,22,NULL)
INSERt INTO tbltest VALUES(3,33,NULL)	INSERT INTO tbltest VALUES(4,33,NULL)
INSERT INTO tbltest VALUES(5,44,NULL)	INSERT INTO tbltest VALUES(6,44,NULL)
INSERT INTO tbltest VALUES(7,55,NULL)	INSERT INTO tbltest VALUES(8,55,NULL)
INSERT INTO tbltest VALUES(9,55,NULL)	INSERT INTO tbltest VALUES(10,55,NULL)

SELECT * FROM tbltest  



-- EXAMPLE 1:
DECLARE CRS CURSOR
FOR
SELECT * FROM tbltest

OPEN CRS 

FETCH NEXT FROM CRS 
FETCH NEXT FROM CRS 
FETCH NEXT FROM CRS 

CLOSE CRS 

DEALLOCATE CRS 









-- EXAMPLE 2:
DECLARE CRS CURSOR
STATIC				-- CURSOR IS LOADED WITH TABLE DATA. CURSOR CANNOT SEE THE UPDATES TO THE BASE TABLE. 
SCROLL				-- CURSOR CAN BE FECTHED IN ANY DIRECTION
GLOBAL				-- CURSOR IS ACCESSIBLE ACROSS MULTIPLE BATCHES WITHIN THE SESSION
FOR
SELECT * FROM tbltest

OPEN CRS 
FETCH FIRST FROM CRS 
FETCH NEXT FROM CRS
FETCH NEXT FROM CRS
FETCH NEXT FROM CRS
FETCH ABSOLUTE 5 FROM CRS 
FETCH LAST FROM CRS 
FETCH PRIOR FROM CRS 
FETCH FIRST FROM CRS 
CLOSE CRS 

DEALLOCATE CRS 


-- HOW TO USE CURSORS IN REAL-WORLD?
-- YOU PRACTICED VIEWS, FUNCTIONS, PARAMETERS WITH STORED PROCEDURES

-- REQ: HOW TO REPORT LIST OF ALL TABLES WITH RESPECTIVE ROW COUNT IN EACH TABLE?
USE [PRODUCT DATABASE] 

SELECT COUNT(*) FROM CUSTOMERS_DATA 
SELECT COUNT(*) AS RCOUNT FROM CUSTOMERS_DATA 
SELECT 'CUSTOMERS_DATA' AS TNAME, COUNT(*) AS RCOUNT FROM CUSTOMERS_DATA 

-- REQ: HOW TO REPORT LIST OF ALL TABLES IN A DATABASE?
SELECT * FROM SYS.TABLES 

-- REQ: HOW TO REPORT LIST OF ALL TABLES WITH RESPECTIVE ROW COUNT IN EACH TABLE?
-- SOLUTION V1: FOR ONE TABLE
DECLARE CRS CURSOR  FOR SELECT NAME FROM SYS.TABLES 
DECLARE @TABNAME SYSNAME, @QUERY NVARCHAR(MAX)
OPEN CRS 
FETCH NEXT FROM CRS INTO @TABNAME		-- THIS IS FETCH OR ACCESS 1ST TABLE NAME INTO THE VARIABLE
SET @QUERY = 'SELECT ''' + @TABNAME+''' AS TNAME, COUNT(*) AS RCOUNT FROM ' + @TABNAME 
EXEC SP_EXECUTESQL @QUERY 
CLOSE CRS 
DEALLOCATE CRS 


-- SOLUTION V2: FOR ALL TABLES IN THE DATABASE
DECLARE CRS CURSOR  SCROLL FOR SELECT NAME FROM SYS.TABLES 
DECLARE @TABNAME SYSNAME, @QUERY NVARCHAR(MAX)
OPEN CRS 
FETCH FIRST FROM CRS INTO @TABNAME	-- THIS IS FETCH OR ACCESS 1ST TABLE NAME INTO THE VARIABLE
WHILE @@FETCH_STATUS = 0			-- THIS IS A GLOBAL VARIABLE. 0 MEANS AS LONG AS CURSOR HAS MORE ROWS. WHILE MEANS "LOOP". 
	BEGIN
	SET @QUERY = 'SELECT ''' + @TABNAME+''' AS TNAME, COUNT(*) AS RCOUNT FROM ' + @TABNAME 
	EXEC SP_EXECUTESQL @QUERY
	FETCH NEXT FROM CRS INTO @TABNAME -- THIS IS TO FETCH NEXT ROW IN THE TABLE INTO THE VARIABLE 
	END
CLOSE CRS 
DEALLOCATE CRS 



-- SOLUTION V3: FOR ALL TABLES IN THE DATABASE
CREATE PROCEDURE USP_REP_TABLEROCOUNTV
AS
BEGIN
DECLARE CRS CURSOR  FOR SELECT NAME FROM SYS.TABLES 
DECLARE @TABNAME SYSNAME, @QUERY NVARCHAR(MAX)
OPEN CRS 
FETCH NEXT FROM CRS INTO @TABNAME	-- THIS IS FETCH OR ACCESS 1ST TABLE NAME INTO THE VARIABLE
WHILE @@FETCH_STATUS = 0			-- THIS IS A GLOBAL VARIABLE. 0 MEANS AS LONG AS CURSOR HAS MORE ROWS [LOOP]
	BEGIN
	SET @QUERY = 'SELECT ''' + @TABNAME+''' AS TNAME, COUNT(*) AS RCOUNT FROM ' + @TABNAME 
	EXEC SP_EXECUTESQL @QUERY		  -- THE SQL STATEMENT IS EXECUTED DYNAMICALLY = DYNAMIC SQL PROGRAM
	FETCH NEXT FROM CRS INTO @TABNAME -- THIS IS TO FETCH NEXT ROW IN THE TABLE INTO THE VARIABLE 
	END
CLOSE CRS 
DEALLOCATE CRS 
END


CREATE TABLE #TABLE (TABNAME SYSNAME, RCOUNT BIGINT)
INSERT INTO #TABLE EXEC USP_REP_TABLEROCOUNTV
SELECT * FROM #TABLE


