CREATE TABLE tbl_ScopeIdenTityV2
(
ID_COL INT identity(1000001,1),
Value_Col INT default 100,
RANK_Col BIT		-- A DATA TYPE USED TO STORE 0s AND 1s
)


INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 DEFAULT VALUES
INSERT INTO tbl_ScopeIdenTityV2 VALUES (200, NULL)
INSERT INTO tbl_ScopeIdenTityV2 VALUES (200, NULL)
INSERT INTO tbl_ScopeIdenTityV2 VALUES (300, NULL)
INSERT INTO tbl_ScopeIdenTityV2 VALUES (300, NULL)


SELECT ID_COL, VALUE_COL, RANK_COL FROM tbl_ScopeIdenTityV2

-- HOW TO GENERATE ROW NUMBERS ?
SELECT *,	ROW_NUMBER()	OVER	(ORDER BY VALUE_COL) AS SEQ1 FROM tbl_ScopeIdenTityV2

SELECT *,	ROW_NUMBER()	OVER	(ORDER BY VALUE_COL) AS SEQ1,
			RANK()			OVER	(ORDER BY VALUE_COL) AS SEQ2 FROM tbl_ScopeIdenTityV2

SELECT *,	ROW_NUMBER()	OVER	(ORDER BY VALUE_COL) AS SEQ1,
			RANK()			OVER	(ORDER BY VALUE_COL) AS SEQ2,
			DENSE_RANK()	OVER	(ORDER BY VALUE_COL) AS SEQ3,
			ROW_NUMBER()	OVER	(partition by VALUE_COL ORDER BY VALUE_COL) AS SEQ4 FROM tbl_ScopeIdenTityV2

