-- STEP 1 : DEFINE A DATABASE
CREATE DATABASE UNIVERSITYDATABASEV1

-- STEP 2: CONNECT TO ABOVE DATABASE
USE UNIVERSITYDATABASEV1

-- STEP 3: HOW TO DEFINE "COURSES" TABLE?
CREATE TABLE tblCourses
(
CourseID	INT UNIQUE,				-- THIS COLUMN DOES NOT ALLOW DUPLICATE VALUES
CourseName	VARCHAR(30)	NOT NULL,	-- THIS COLUMN DOES NOT ALLOW NULLS = MANDATORY COLUMN
CourseDur	INT			NULL		-- THIS COLUMN ALLOW NULL VALUES = OPTIONAL COLUMN
)

-- STEP 4: INSERT DATA INTO ABOVE TABLE
INSERT INTO tblcourses VALUES (101, 'COMPUTERS', 120)
INSERT INTO tblcourses VALUES (102, 'ROBOTICS', 180)
INSERT INTO tblcourses VALUES (103, 'CIVIL', 120)

-- STEP 5: HOW TO REPORT OR VERIFY DATA FROM ABOVE TABLE?
SELECT * FROM tblcourses

-- STEP 6: HOW TO TEST UNIQUE (KEY) CONSTRAINT ?
INSERT INTO tblcourses VALUES (103, 'ELECTRONICS', 120)		-- ERROR. REASON : COURSE_ID IS DUPLICATED.
INSERT INTO tblcourses VALUES (104, 'ELECTRONICS', 120)		-- NO ERROR

-- STEP 7: HOW TO TEST NULL VALUES & NULL CONSTRAINT?
INSERT INTO tblcourses VALUES (105, NULL, 120)				-- ERROR. REASON : COURSE_NAME CANNOT BE NULL.
SELECT * FROM tblcourses

-- STEP 8: HOW TO DEFINE A "STUDENTS" TABLE, MAKE IT RELATED TO THE ABOVE "COURSES" TABLE ?
CREATE TABLE tblStudents
(
STD_ID		INT		PRIMARY KEY,				-- THIS COLUMN DOES NOT ALLOW DUPLICATES AND DOES NOT ALLOW NULL VALUES
STD_NAME	VARCHAR(30) NOT NULL,				-- THIS COLUMN DOES NOT ALLOW NULL VALUES. MEANS : MANDATORY COLUMN
STD_AGE		TINYINT	CHECK (STD_AGE >= 18),		-- THIS COLUMN SHOULD HAVE MINIMUM AGE : 18  [RANGE OF TINYINT : 0 TO 255]
STD_GENDER	CHAR(6)	CHECK (STD_GENDER = 'M' OR STD_GENDER = 'F'), -- THIS COLUMN SHOULD HAVE EITHER M' OR 'F' VALUE
STD_CRS_ID	INT		REFERENCES tblCourses(CourseID)			-- note: THIS IS AN EXTRA COLUMN. REFERENCES MEANS "DEPENDS ON"
) 

-- STEP 9: HOW TO INSERT DATA INTO ABOVE TABLE?
INSERT TBLSTUDENTS VALUES (1001, 'SAI', 34, 'M', 101)   
INSERT TBLSTUDENTS VALUES (1002, 'JON', 34, 'F', 101)   
INSERT TBLSTUDENTS VALUES (1003, 'JOHNE', 34, 'M', 102)
INSERT TBLSTUDENTS VALUES (1003, null, 34, 'M', 102)				-- ERROR. REASON : NULLABILITY
INSERT TBLSTUDENTS VALUES (1005, 'JOHNEY', 34, 'M', 103)
INSERT TBLSTUDENTS VALUES (1006, 'JENY', 24, 'M', 3333)				-- ERROR. REASON : INVALID COURSE ID FROM COURSES TABLE

-- IN A BATCH : THE SUCCESS OR FAILURE OF ONE STATEMENT DOES NOT STOP EXEUTION OF OTHER STATEMENTS
-- WHICH OF THE CONSTRAINTS HAS MORE PRIORITY?		OPTION 1 : PRIMARY KEY			OPTION 2:	NULL & NOT NULL
-- STEP 10 : TO VERIFY ABOVE TABLE DATA ? 
SELECT * FROM TBLSTUDENTS


-- STEP 10: HOW TO DEFINE A "STAFF" TABLE, MAKE IT RELATED TO THE ABOVE "COURSES" TABLE ?
CREATE TABLE tblstaff 
(
StfID	INT	IDENTITY(1001,1) PRIMARY KEY,	-- THIS COLUMN DOES NOT ALLOW DUPLICATES AND DOES NOT ALLOW NULL VALUES
StfName varchar(30) NOT NULL,				-- THIS COLUMN VALUE IS MANDATORY. MEANS, IT DOES NOT ALLOW NULL VALUES
StfAge	tinyint		CHECK(StfAge >= 28),	-- THIS COLUMN VALUE SHOULD BE MINIMUM 28  [RANGE: 0 TO 255]
StfGender char		CHECK(StfGender IN ('M','F')) DEFAULT 'M',	-- THIS COLUMN VALUE SHOULD BE EITHER "M" OR "F"
StfCourseID int		REFERENCES tblcourses(CourseID)  -- THIS EXTRA COLUMN VALUE SHOULD BE FROM THE COURSES TABLES COURSEID COLUMN
)

-- STEP 11: HOW TO INSERT DATA INTO ABOVE TABLE?
INSERT INTO tblstaff VALUES ('SAI', 29, 'M', 101), ('JOHN', 29, 'M', 102),( 'AMIN', 29, 'M', 102)	
SELECT * FROM tblstaff

-- RULE : WHENEVER WE NEED DEFAULT VALUES FOR COLUMNS, SPECIFY REMAINING COLUMNS AND THEIR VALUES. 

INSERT INTO tblstaff(StfName, StfAge, StfCourseID) VALUES ( 'AMINI', 39, 103)	-- THE MISSING COLUMN WILL TAKE THE DEFAULT VALUE
INSERT INTO tblstaff(StfName, StfAge, StfCourseID) VALUES ( 'AMINISHA', 41, 103)-- THE MISSING COLUMN WILL TAKE THE DEFAULT VALUE
SELECT * FROM tblstaff

INSERT INTO tblstaff VALUES ('TEENA', 19, 'F', 103) -- ERROR. INVALID COURSE AGE
SELECT * FROM tblstaff

INSERT INTO tblstaff VALUES ('HEENA', 39, 'F', 66666) -- ERROR. INVALID COURSE ID
SELECT * FROM tblstaff

-- HOW TO DEFINE EXAMINATIONS TABLE, RELATE OR LINK TO ABOVE TWO TABLES?



-- TO VERIFY THE RELATIONS BETWEEN TABLES : WE NEED TO USE "DATABASE DIAGRAMS"

/*
LAUNCH SSMS > CONNECT TO SQL SERVER > OBJECT EXPLORER > EXPAND DATABASES >
EXPAND REQUIRED DATABASE > RIGHT CLICK "DATABASE DIAGRAM" > 
INSTALL DIAGRAM SUPPORT > CLICK "YES" WHEN PROMPTED.
RIGHT CLICK "DATABASE DIAGRAM" >  NEW DATABASE DIAGRAM >
SELECT REQUIRED TABLES > ADD. THEN WE SEE THE "ER DIAGRAM" 
ENTITY RELATIONSHIP DIAGRAM.

TO VERIFY THE RELATIONS FOR COLUMNS:
		RIGHT CLICK EACH ARROW > PROPERTIES >  TABLES & COLUMN SPECFICIATIONS:
					FOREIGN KEY TABLE, FOREIGN KEY COLUMN
					CANDIDATE KEY TABLE, CANDIDATE KEY COLUMN
*/
















