CREATE DATABASE TRANDB11

USE TRANDB11

create table Reservation
( 
Aircraft_Code varchar(10),
No_of_Seats int,
Class_Code varchar(10)
)


-- ITEM 1:	EXAMPLES FOR AUTOCOMMIT TRANSACTIONS. means AUTO SAVE OF TABLE DATA INTO THE DATABASE.  
INSERT INTO Reservation VALUES ('AI11', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI12', 22, 'ECO')
INSERT INTO Reservation VALUES ('AI13', 23, 'ECO')

-- ITEM 2:	EXAMPLES FOR EXPLICIT TRANSACTIONS
BEGIN TRANSACTION T1
INSERT INTO Reservation VALUES ('AI14', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI15', 22, 'ECO')
COMMIT TRANSACTION

BEGIN TRANSACTION T2

INSERT INTO Reservation VALUES ('AI16', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI17', 22, 'ECO')
ROLLBACK TRANSACTION

SELECT * FROM Reservation			


-- ITEM #3: EXAMPLE FOR CONDITIONAL COMMIT (EXPLICIT TRANSACTION):
BEGIN TRANSACTION T1
INSERT INTO Reservation VALUES ('AI127', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI129', 23, 'ECO')
IF @@ERROR = 0			-- MEANS, IF THERE ARE NO ERRORS.  @@error is a predefined System Global Variable
	COMMIT
ELSE
	ROLLBACK			-- to cancel or undo


-- ITEM #4: EXAMPLE FOR CONDITIONAL COMMIT (IMPLICIT TRANSACTION):
SET IMPLICIT_TRANSACTIONS ON						-- THIS STATEMENT IS USED TO ACTIVATE THE IMPLICIT TRANSACTIONS			
INSERT INTO Reservation VALUES ('AI127', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI129', 23, 'ECO')
IF @@ERROR = 0			-- MEANS, IF THERE ARE NO ERRORS
	COMMIT
ELSE
	ROLLBACK


SET IMPLICIT_TRANSACTIONS OFF						-- THIS STATEMENT IS USED TO DEACTIVATE THE IMPLICIT TRANSACTIONS	



TRUNCATE TABLE Reservation
GO

INSERT INTO Reservation VALUES ('AI01', 21, 'ECO')
INSERT INTO Reservation VALUES ('AI02', 22, 'ECO')
INSERT INTO Reservation VALUES ('AI03', 23, 'ECO')

SELECT * FROM Reservation

-- ITEM #5: OPEN TRANSACTIONS : SUCH TRANSACTIONS WHICH ARE STARTED BUT NEITHER COMMITTED NOR ROLLEDBACK.
-- IMPACT OF OPEN TRANSACTIONS: QUERY BLOCKING

BEGIN TRANSACTION T1
INSERT INTO Reservation VALUES ('AI104', 31, 'ECO')
INSERT INTO Reservation VALUES ('AI105', 32, 'ECO')

-- NOW, GO TO A NEW QUERY WINDOW  [CTRL + N]  >> 
	-- TYPE THIS STATEMENT ::   SELECT * FROM Reservation
	-- EXECUTE
	-- THEN YOU SEE QUERY BLOCKING. 
	-- CANCEL THE QUERY.. [FILE MENU > QUERY > CANCEL .

-- SOLUTION TO QUERY BLOCKING: USE "LOCK HINTS" :: "NOLOCK" or "READPAST" LOCK HINTS

-- RUN BELOW TWO QUERIES IN THE PREVIOUSLY CREATED NEW QUERY WINDOW : 
SELECT * FROM Reservation WITH (NOLOCK)		-- NO BLOCKING. BUT WE SEE UNCOMITTED DATA =  DIRTY READS = BAD DATA.

SELECT * FROM Reservation WITH (READPAST)	-- ** NO BLOCKING. WE SEE PREVIOUSLY COMITTED DATA ONLY.


-- TO AVOID QUERY BLOCKING :	 USE LOCK HINTS  [NOLOCK, READPAST]
-- TO RESOLVE QUERY BLOCKING:	 COMIT OR ROLLBACK THE TRANSACTION

rollback

-- DISTRIBUTED TRANSACTION  :	A TRANSACTION THAT SPANS OR WORKS WITH MORE THAN ONE SQL SERVER.
-- LINKED SERVERS			:	SERVER OBJECTS USED TO "LINK" OR "COMMUNICATE" BETWEEN MORE THAN ONE
								SERVER FOR SELECT, DML, DDL OPERATIONS.

								TO IMPLEMENT DISTRIBUTED TRANSACTIONS, WE NEED LINKED SERVERS.

								STEPS TO CREATE LINKED SERVER:
								STEP 1: LAUNCH SSMS > CONNECT TO YOUR LOCAL SERVER > SERVER OBJECTS >
										RIGHT CLICK > NEW LINKED SERVER > SPECIFY ONLINE SERVER NAME
										SECURITY : SPECIFY LOGIN NAME AND PASSWORD
										SERVER OPTION : DATA ACCESS = TRUE
														RPC = TRUE [REMOTE PROCEDURE CALL : FOR READS]
														RPC OUT = TRUE [REMOTE PROCEDURE CALL OUT : FOR DMLs]
								
								STEP 2: RIGHT CLICK ABOVE LINKED SERVER > TEST CONNECTION

								STEP 3: RUN THE REQUIRED QUERIES USING THE LINKED SERVER.


Please use below LIVE  Server  (Online Lab) details:

LAUNCH SSMS tool >> provide below details :

Server Name:       sqlschool.database.windows.net
Login Name:        sql_school 
PASSWORD:          szurte321671$$$

ROLLBACK
-- A QUERY WITH MULTIPLE SERVERS:

CREATE DATABASE DB1

USE DB1 

CREATE TABLE TBLCOURSES
(
COURSE_ID INT PRIMARY KEY,			
COURSE_NAME VARCHAR(30) NOT NULL,	
COURSE_DUR INT CHECK (COURSE_DUR = 120  OR COURSE_DUR = 180)
)

INSERT INTO TBLCOURSES VALUES (101, 'COMPUTERS', 120),  (102, 'ROBOTICS', 180)

SELECT * FROM TBLCOURSES

-- A SAMPLE QUERY TO TEST DISTRIBUTED TRANSACTIONS:
SELECT * FROM [sqlschool.database.windows.net].PracticeDatabase.RemoteSchema.TBLSTUDENTS

-- A SAMPLE QUERY TO JOIN MULTIPLE SERVERS  = REMOTE JOIN
SELECT * FROM TBLCOURSES AS T1
INNER JOIN 
[SQLSCHOOL\LOCAL_SERVER2].DB2.RemoteSchema.TBLSTUDENTS AS T2
ON
T1.COURSE_ID = T2.STD_COURSE_ID 


-- PARTICIPANTS FOR SQL DBA :  PLEASE ENSURE YOU ARE PERFECT WITH ALL BASIC CONCEPTS TILL DATE.

-- PARTICIPANTS FOR POWER BI:  PLEASE REVISE SQL BASICS, CONSTRAINTS, JOINS. TOMORROW : CASE STUDY WITH EXCEL
-- PARTICIPANTS FOR MSBI:		PLEASE REVISE SQL BASICS, CONSTRAINTS, JOINS. TOMORROW : CASE STUDY WITH EXCEL

-- PARTITICIPANTS FOR T-SQL B,C,D : PLEASE ENSURE YOU ARE PERFECT WITH ALL BASIC CONCEPTS TILL DATE.

TOMORROW	:	7 15 PM   [15 MINS EARLY] FOR SQL DBAs  + T-SQL PLAN B,C,D   =	AGENDA	:	INDEX ARCH"

TOMORROW	:	T-SQL PLAN A,B,C,D, + POWER BI + MSBI :	8 PM		30 mins @ CASE STUDY 
