USE [PRODUCT DATABASE]
GO

SELECT * FROM SALES_DATA
SELECT * FROM PRODUCTS_DATA
SELECT * FROM CUSTOMERS_DATA
SELECT * FROM TIME_DATA

/*   BEFORE YOU PROCEED :: GENERATE A DATABASE DIAGRAM FOR THE ABOVE MENTIONED TABLES. READ THE RELATIONS */

-- QUERY  #1: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT  * FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]


-- QUERY  #2: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName],[SalesAmount]   FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]


-- QUERY  #3: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName], SUM([SalesAmount]) AS TOTAL_SALES  FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
GROUP BY [EnglishProductName]

-- QUERY  #4: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName], CONVERT(INT, SUM([SalesAmount])) AS TOTAL_SALES  FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
GROUP BY [EnglishProductName]


-- QUERY  #5: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName], '$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
GROUP BY [EnglishProductName]


-- QUERY 6: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT CALENDARYEAR, [EnglishProductName],
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY CALENDARYEAR, [EnglishProductName]



-- QUERY 7: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- QUERY 8: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(DATE,[FullDateAlternateKey]) AS SALE_DAY, [EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- QUERY 9: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, [EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- QUERY 9: JOINING 4 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR FOR MARRIED FEMALE CUSTOMERS ?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, 
[EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
INNER JOIN
CUSTOMERS_DATA 
ON
CUSTOMERS_DATA.CustomerKey = SALES_DATA.CustomerKey
WHERE CUSTOMERS_DATA.GENDER = 'F' AND CUSTOMERS_DATA.MaritalStatus = 'M'
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- QUERY 10:
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, 
[EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA] AS P
INNER JOIN
[dbo].[SALES_DATA] AS S
ON
P.PRODUCTKEY = S.[ProductKey]
INNER JOIN 
TIME_DATA  AS T
ON
T.TIMEKEY = S.ORDERDATEKEY
INNER JOIN
CUSTOMERS_DATA  AS C
ON
C.CustomerKey = S.CustomerKey
WHERE C.GENDER = 'F' AND C.MaritalStatus = 'M'
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- QUERY 10: REPORT SALES FOR EACH YEAR, QUARTER, MONTH, DAY FOR MAXIMUM PRICED PRODUCTS ? 
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, 
[EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA] AS P
INNER JOIN
[dbo].[SALES_DATA] AS S
ON
P.PRODUCTKEY = S.[ProductKey]
INNER JOIN 
TIME_DATA  AS T
ON
T.TIMEKEY = S.ORDERDATEKEY
INNER JOIN
CUSTOMERS_DATA  AS C
ON
C.CustomerKey = S.CustomerKey
WHERE C.GENDER = 'F' AND C.MaritalStatus = 'M' AND P.DealerPrice IN ( SELECT MAX(DealerPrice) FROM PRODUCTS_DATA)
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- REQ: HOW TO REPORT DATA TO END USERS?
-- SOLUTION : SAVE THE QUERY IN THE DATABASE. USE THIS QUERY FOR REPORTING.

CREATE VIEW VW_SALES2
AS
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, 
[EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA] AS P
INNER JOIN
[dbo].[SALES_DATA] AS S
ON
P.PRODUCTKEY = S.[ProductKey]
INNER JOIN 
TIME_DATA  AS T
ON
T.TIMEKEY = S.ORDERDATEKEY
INNER JOIN
CUSTOMERS_DATA  AS C
ON
C.CustomerKey = S.CustomerKey
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


SELECT * FROM VW_SALES







-- QUERY 11: REPORT SALES FOR EACH YEAR, QUARTER, MONTH, DAY FOR MAXIMUM DEALER PRICED PRODUCTS WITH MINIMUM LIST PRICE ? 
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, 
[EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA] AS P
INNER JOIN
[dbo].[SALES_DATA] AS S
ON
P.PRODUCTKEY = S.[ProductKey]
INNER JOIN 
TIME_DATA  AS T
ON
T.TIMEKEY = S.ORDERDATEKEY
INNER JOIN
CUSTOMERS_DATA  AS C
ON
C.CustomerKey = S.CustomerKey
WHERE C.GENDER = 'F' AND C.MaritalStatus = 'M' AND 
P.DealerPrice IN ( SELECT MAX(DealerPrice) FROM PRODUCTS_DATA WHERE LISTPRICE IN (SELECT MAX(LISTPRICE) FROM PRODUCTS_DATA))
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]
