/*
MERGE	:	A MECHANISM TO COMPARE TABLES.	IDENTIFY MATCHING DATA AND MISSING DATA.
			PERFORM DML OPERATIONS ON THIS MATCHING & / MISSING DATA.
			INCREMENTAL CHANGES = INCREMENTAL LOADS.
*/

CREATE TABLE tblOrders  
(
  ID INT NOT NULL PRIMARY KEY,
  TitleTag NVARCHAR(100) NOT NULL,
  Measure INT NOT NULL DEFAULT 0
)

CREATE TABLE tblInventory  
(
  ID INT NOT NULL PRIMARY KEY,
  TitleTag NVARCHAR(100) NOT NULL,
  Measure INT NOT NULL DEFAULT 0
)


INSERT INTO tblOrders VALUES
  (111, 'Comedy', 1),  (112, 'NEGOT', 1),  
  (113, 'BUSINESS', 1)

INSERT tblInventory VALUES
  (113, 'BUSN PROFILES', 100),  (114, 'PB CHAPTER BKS', 100),
  (115, 'BEG READER HC', 100),  (116, 'Literature', 100);


SELECT * FROM tblOrders				-- 3 ROWS
SELECT * FROM tblInventory			-- 4 ROWS

/*
REQ: COMPARE ABOVE TABLES BASED ON ID COLUMN.
FOR MATCHING IDs :	ADD MEASURE COLUMN VALUES, STORE UPDATED VALUE IN INVENTORY TABLE
FOR UNMATCHED IDs : INSERT SUCH ROWS FROM ORDERS TABLE INTO INVENTORY TABLE
*/

-- SOLUTION:
MERGE tblInventory			-- this is the target table
USING tblOrders				-- this is the source table  [REFERENCE TABLE]
ON
tblInventory.ID = tblOrders.ID
WHEN MATCHED	 THEN	UPDATE SET tblInventory.Measure =  tblInventory.Measure + tblOrders.Measure
WHEN NOT MATCHED THEN	INSERT VALUES (tblOrders.ID, tblOrders.TitleTag, tblOrders.Measure);


-- IN OUR EXAMPLE, WE HAVE 1 MATCHING ROW DATA  ++ 2 MISSING ROW DATA
SELECT * FROM tblInventory			-- 6 ROWS

SELECT *, IIF(MEASURE = 1, 'ROW FROM ORDERS', 'ROW FROM INVENTORY') AS ROW_STATUS  FROM tblInventory

SELECT *,	CASE	WHEN MEASURE = 1	THEN 'ROW FROM ORDERS'
					WHEN MEASURE = 100	THEN 'ROW FROM INVENTORY'
					WHEN MEASURE = 101	THEN 'ROW FROM ORDERS & INVENTORY' 
					ELSE
					'NO GRADE AVAILABLE'
			END 
			AS ROW_STATUS  FROM tblInventory

-- RANK FUNCTIONS, PIVOT FUNCTION, STRING FUNCTIONS








