
CREATE TABLE #ServiceSales (ServiceType VARCHAR(80), SalesYear INT, NoOfLeads int);
 
INSERT #ServiceSales VALUES	('SQL SEVER TRAINING', 2014, 1200),('SQL SEVER TRAINING', 2015, 1900),
							('SQL SEVER TRAINING', 2016, 2300),('SQL SEVER TRAINING', 2017, 2400);
INSERT #ServiceSales VALUES	('SQL DBA TRAINING', 2014, 4000),('SQL DBA TRAINING', 2015, 5500),
							('SQL DBA TRAINING', 2016, 5900),('SQL DBA TRAINING', 2017, 6000);
INSERT #ServiceSales VALUES	('MSBI TRAINING', 2014, 900),('MSBI TRAINING', 2015, 1800),
							('MSBI TRAINING', 2016, 2300),('MSBI TRAINING', 2017, 2900);
INSERT #ServiceSales VALUES	('POWER BI TRAINING', 2016, 150), ('POWER BI TRAINING', 2017, 100);
INSERT #ServiceSales VALUES	('CASE STUDIES n PROJECTS', 2015, 1000),('CASE STUDIES n PROJECTS', 2016, 2800),
							('CASE STUDIES n PROJECTS', 2017, 4000)

SELECT * FROM #ServiceSales


/*
PIVOT IS A MECHANISM TO CONVERT UNIQUE COLUMN VALUES TO COLUMNS. 
EX: 'SalesYear' COLUMN VALUES ARE : 2014, 2015, 2016, 2017
THESE COLUMN VALUES CAN BE CONVERTED INTO COLUMNS USING "PIVOT".

SYNTAX:
		SELECT <COLUMNLIST> FROM <TABLE>OR<VIEW>
		PIVOT (<AGGREGATION ON PIVOT COLUMN>) 
		FOR <COLUMN WHOSE VALUES SHOULD BE NEW COLUMNS>  AS <CorrelationName> 
*/

SELECT * FROM #ServiceSales
PIVOT (Sum(NoOfLeads)
	  FOR SalesYear IN ([2014])
	  )  AS PivotQuery

SELECT * FROM #ServiceSales
PIVOT (Sum(NoOfLeads)
	FOR SalesYear IN ([2014],[2015])
	  )  AS PivotQuery

SELECT * FROM #ServiceSales
PIVOT (Sum(NoOfLeads)
FOR SalesYear IN ([2014],[2015],[2016],[2017]))  AS PivotQuery


SELECT *, IIF(NoOfLeads > 2000, 'not GOOD COUNT', 'GOOD COUNT') AS LEAD_GRADE  FROM #ServiceSales 

SELECT *, CASE	WHEN		NoOfLeads < 1000  THEN 'LOW LEADS'
				WHEN		NoOfLeads BETWEEN 1001 AND 2000 THEN 'MODERATE LEADS'
				WHEN		NoOfLeads	> 2001 THEN 'HIGH LEADS'
				END 
			AS LEAD_GRADE  FROM #ServiceSales 


-- SYNONYMS ARE PERMENANT ALTERNATE NAMES TO DATABASE OBJECTS.
-- USED FOR DATA ABASTRACTION [TO HIDE OBJECT NAMES FROM END USERS]

CREATE SYNONYM synTable FOR tbl_ScopeIdenTity

SELECT * FROM tbl_ScopeIdenTity
SELECT * FROM synTable

INSERT INTO tbl_ScopeIdenTity VALUES (300, NULL)
INSERT INTO synTable VALUES (300, NULL)


CREATE INDEX INDEX1 ON synTable(VALUE_COL)			-- ERROR
CREATE INDEX INDEX1 ON tbl_ScopeIdenTity(VALUE_COL)	-- no error


-- LIMITATIONS OF SYSNONYMS :  WE CAN USE SYNONYMS ONLY FOR DATA RETREIVAL AND DATA MANUPULATIONS. 
-- SYNONYMS CAN BE AUDITTED:
SELECT * FROM SYS.synonyms WHERE OBJECT_ID = OBJECT_ID('tbl_ScopeIdenTity')










