create table Reservation1
(
Aircraft_Code varchar(10), No_of_Seats int, Class_Code varchar(10)
)

create table Reservation2
(
Aircraft_Code varchar(10), No_of_Seats int, Class_Code varchar(10)
)

-- REQUIREMENT 1: WHENEVER WE INSERT DATA INTO 1ST TABLE, AUTO INSERT SAME DATA INTO 2ND TABLE.
CREATE TRIGGER trgAdditioanOperation
ON Reservation1
FOR INSERT					-- THIS MEANS, IN ADDITION TO "INSERT" EVENT
AS
BEGIN
INSERT INTO Reservation2 SELECT * FROM INSERTED 
END 

-- HOW TO TEST ABOVE TRIGGER?
INSERT Reservation1 VALUES ('AI01', 11, 'ECO');  
INSERT Reservation1 VALUES ('AI02', 22, 'ECO')

SELECT * FROM Reservation1
SELECT * FROM Reservation2


-- REQ 2: HOW TO DISABLE UPDATES & DELETES ON A TABLE?
-- REQUIREMENT: RESERVATIONS ONCE INSERTED CANNOT BE MODIFIFED AND CANNOT BE CANCELLED.
CREATE TRIGGER trigPreventOps 
ON Reservation1
INSTEAD OF UPDATE, DELETE
AS
	BEGIN
	PRINT 'RESERVATIONS ONCE APPROVED CANNOT BE MODIFIFED OR CANCELLED'
	PRINT 'CONTACT YOUR ADMIN.'
	END 

	
-- HOW TO TEST ABOVE TRIGGER
	DELETE FROM Reservation1				-- actual delete will not go thru

	SELECT * FROM Reservation1


-- HOW TO DISABLE A TRIGGER?
	DISABLE TRIGGER trigPreventOps ON Reservation1

				-- NOW WE CAN DELETE DATA FROM THE TABLE
				DELETE FROM Reservation1
				SELECT * FROM Reservation1

-- HOW TO ENABLE A TRIGGER?
	ENABLE TRIGGER trigPreventOps ON Reservation1

-- HOW TO LIST ALL TRIGGERS IN A DATABASE?
SELECT * FROM SYS.TRIGGERS 



/* DATABASE SCOPED DDL TRIGGERS */
CREATE TRIGGER TRIG_DB_LEVEL
ON DATABASE						-- DEFINING THE TRIGGER IN THE CURRENTLY CONNECTED DATABASE
FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
PRINT 'GIVEN DATABASE LEVEL DDL OPERATION IS SUCCESSFUL.'


-- TO TEST ABOVE TRIGGER?
CREATE TABLE RESERVATION3 (CRAFTCODE VARCHAR(30), SEATS INT, CLASS SQL_VARIANT)









/* SERVER SCOPED DDL TRIGGERS */
CREATE TRIGGER TRIG_SRV2_LEVEL2
ON ALL SERVER					-- DEFINING THE TRIGGER FOR THE ENTIRE SERVER (INSTANCE)
FOR CREATE_DATABASE, ALTER_DATABASE, DROP_DATABASE
AS
PRINT 'GIVEN SERVER LEVEL DDL OPERATION IS SUCCESSFUL.'



-- TO TEST ABOVE TRIGGER?
CREATE DATABASE DATABASETEST22622