USE [PRODUCT DATABASE]
GO

SELECT * FROM SALES_DATA
SELECT * FROM PRODUCTS_DATA
SELECT * FROM CUSTOMERS_DATA
SELECT * FROM TIME_DATA


/*   BEFORE YOU PROCEED :: GENERATE A DATABASE DIAGRAM FOR THE ABOVE MENTIONED TABLES. READ THE RELATIONS */






-- QUERY  #1: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT *
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey


-- QUERY #2
SELECT EnglishProductName, SalesAmount
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey



-- QUERY #3
SELECT EnglishProductName, SUM(SalesAmount)
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
GROUP BY EnglishProductName


-- QUERY #4
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
GROUP BY EnglishProductName



-- QUERY #5 : HOW TO REPORT PRODUCT WISE TOTAL SALES ABOVE 1000 USD?
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
GROUP BY EnglishProductName
HAVING SUM(SalesAmount) > 1000


-- QUERY #6 : HOW TO REPORT PRODUCT WISE TOTAL SALES AND TOTAL TAX ABOVE 1000 USD?
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES, SUM(TAXAMT) AS TOTAL_TAX
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
GROUP BY EnglishProductName
HAVING 
SUM(SalesAmount) > 1000  AND SUM(TAXAMT)  > 1000


-- QUERY #7 : HOW TO REPORT PRODUCT WISE TOTAL SALES AND TOTAL TAX ABOVE 1000 USD?
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES, SUM(TAXAMT) AS TOTAL_TAX
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
GROUP BY EnglishProductName
HAVING 
SUM(SalesAmount) > 1000  AND SUM(TAXAMT)  > 1000
ORDER BY SUM(SalesAmount) DESC						-- HIGHEST ON TOP


-- QUERY #8 : HOW TO REPORT PRODUCT WISE TOTAL SALES AND TOTAL TAX ABOVE 1000 USD?
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES, SUM(TAXAMT) AS TOTAL_TAX
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
GROUP BY EnglishProductName
HAVING 
SUM(SalesAmount) > 1000  AND SUM(TAXAMT)  > 1000
ORDER BY 2 DESC					-- ORDERING THE DATA BY USING COLUMN CARDINAL POSITION. 


-- QUERY 9:  WRITE A QUERY TO REPORT SUM OF SALES AND TAX FOR SUCH PRODUCTS WITH MAXIMUM DEALER PRICE ?
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES, SUM(TAXAMT) AS TOTAL_TAX
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
WHERE
PRODUCTS_DATA.DealerPrice 
		IN ( SELECT MAX(DealerPrice) FROM PRODUCTS_DATA)
GROUP BY EnglishProductName
HAVING 
SUM(SalesAmount) > 1000  AND SUM(TAXAMT)  > 1000
ORDER BY 3 DESC

/*
QUERY EXECUTION ORDER:
		VALIDATION OF COLUMNS
		FROM
		JOIN
		WHERE
		GROUP BY
		HAVING
		ORDER BY & SELECT			:: ONLY THESE STATEMENTS SUPPORT COLUMN ALIASES
		PIVOT
*/


-- QUERY 10:  WRITE A QUERY TO REPORT SUM OF SALES AND TAX FOR SUCH PRODUCTS WITH MAXIMUM DEALER PRICE BUT NOT FOR MINIMAL LIST PRICE ?
-- NESTED SUB QUERY
SELECT EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES, SUM(TAXAMT) AS TOTAL_TAX
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
WHERE
PRODUCTS_DATA.DealerPrice 
		IN ( SELECT MAX(DealerPrice) FROM PRODUCTS_DATA WHERE  LISTPRICE NOT IN ( SELECT MIN(LISTPRICE) FROM PRODUCTS_DATA ) )
GROUP BY EnglishProductName
HAVING 
SUM(SalesAmount) > 1000  AND SUM(TAXAMT)  > 1000





-- QUERY #11 : HOW TO REPORT YEAR WISE, CUSTOMER WISE, PRODUCT WISE TOTAL SALES AND TOTAL TAX ABOVE 1000 USD?
SELECT CalendarYear, GENDER,  EnglishProductName, SUM(SalesAmount) AS TOTAL_SALES, SUM(TAXAMT) AS TOTAL_TAX
FROM SALES_DATA 
INNER JOIN
PRODUCTS_DATA
ON
SALES_DATA.ProductKey = PRODUCTS_DATA.ProductKey
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TimeKey = SALES_DATA.OrderDateKey
INNER JOIN
CUSTOMERS_DATA
ON
SALES_DATA.CustomerKey = Customers_DATA.CUSTOMERKEY
GROUP BY CalendarYear, EnglishProductName, GENDER 
HAVING 
SUM(SalesAmount) > 1000  AND SUM(TAXAMT)  > 1000
ORDER BY 4 DESC, 5 ASC



-- QUERY 12: HOW TO SAVE ABOVE QUERY?
CREATE VIEW VQ_SALES_TAX_REPORT
AS
SELECT T.CalendarYear, C.GENDER,  P.EnglishProductName, SUM(S.SalesAmount) AS TOTAL_SALES, SUM(S.TAXAMT) AS TOTAL_TAX
FROM SALES_DATA  AS S 
INNER JOIN
PRODUCTS_DATA AS P
ON
S.ProductKey = P.ProductKey
INNER JOIN
TIME_DATA  AS T
ON
T.TimeKey = S.OrderDateKey
INNER JOIN
CUSTOMERS_DATA AS C
ON
S.CustomerKey = C.CUSTOMERKEY
GROUP BY T.CalendarYear, P.EnglishProductName, C.GENDER 
HAVING 
SUM(S.SalesAmount) > 1000  AND SUM(S.TAXAMT)  > 1000


