-- IMPORTANT SYSTEM FUNCTIONS  [DATE & TIME]

SELECT GETDATE()  -- -- REPORTS DATE AND TIME UPTO ms

--  CONVERT IS A SYSTEM BUILT-IN FUNCTION USED TO CONVERT DATA FROM ONE DATA TYPE TO ANOTHER DATA TYPE.
SELECT CONVERT(DATE, GETDATE())				-- REPORTS ONLY DATE
SELECT CONVERT(TIME, GETDATE())				-- REPORTS ONLY TIME UPTO ns
SELECT CONVERT(DATETIME, GETDATE())			-- REPORTS DATE AND TIME UPTO ms
SELECT CONVERT(DATETIME2, GETDATE())		-- REPORTS DATE AND TIME UPTO ns

--  CAST IS A SYSTEM BUILT-IN FUNCTION USED TO CONVERT DATA FROM ONE TYPE TO ANOTHER TYPE.
SELECT CAST(GETDATE() AS DATE)				-- REPORTS ONLY DATE
SELECT CAST(GETDATE() AS TIME)				-- REPORTS ONLY TIME UPTO ns
SELECT CAST(GETDATE() AS DATETIME)			-- REPORTS DATE AND TIME UPTO ms
SELECT CAST(GETDATE() AS DATETIME2)			-- REPORTS DATE AND TIME UPTO ns



-- DATE TIME CONVERSION STYLES (FOR BI REPORT DEVELOPERS):
SELECT CONVERT(VARCHAR(30), GETDATE(), 101)			-- mm/dd/yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 102)			-- yyyy.mm.dd
SELECT CONVERT(VARCHAR(30), GETDATE(), 103)			-- dd/mm/yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 104)			-- dd.mm.yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 105)			-- dd-mm-yyyy
SELECT CONVERT(VARCHAR(30), GETDATE(), 106)			-- dd MON YYYY
SELECT CONVERT(VARCHAR(30), GETDATE(), 107)			-- MON dd, YYYY

SELECT CONVERT(VARCHAR(30), GETDATE(), 108)			-- TIME 

SELECT CONVERT(VARCHAR(30), GETDATE(), 109)			-- DATE & TIME



-- OTHER DATE & TIME FUNCTIONS: 
SELECT YEAR(GETDATE())
SELECT MONTH(GETDATE())
SELECT DAY(GETDATE())

SELECT DATEDIFF(d, '2016-09-07 20:46:51.653', '2018-12-31 20:46:51.653') -- REPORTS DIFFERENCE IN DAYS
SELECT DATEDIFF(M, '2016-09-07 20:46:51.653', '2018-09-07 20:46:51.653') -- REPORTS DIFFERENCE IN MONTHS
SELECT DATEDIFF(YYYY, '2016-09-07 20:46:51.653', '2018-09-07 20:46:51.653') -- REPORTS DIFFERENCE IN YEARS

SELECT DATEADD(d, 60, '2018-01-31')		-- ADDS n NUMBER OF DAYS TO EXISTING DATE
SELECT DATEADD(d, 1, GETDATE())			-- TO GET TOMORROW'S DATE
SELECT DATEADD(d, -1, GETDATE())		-- TO GET YESTERDAY'S DATE


