USE [PRODUCT DATABASE]
GO

SELECT * FROM SALES_DATA
SELECT * FROM PRODUCTS_DATA
SELECT * FROM CUSTOMERS_DATA
SELECT * FROM TIME_DATA

/*   BEFORE YOU PROCEED :: GENERATE A DATABASE DIAGRAM FOR THE ABOVE MENTIONED TABLES. READ THE RELATIONS */

-- QUERY  #1: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT  * FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]


-- QUERY  #2: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName],[SalesAmount]   FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]


-- QUERY  #3: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName], SUM([SalesAmount]) AS TOTAL_SALES  FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
GROUP BY [EnglishProductName]


-- QUERY  #4: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName], CONVERT(INT, SUM([SalesAmount])) AS TOTAL_SALES  FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
GROUP BY [EnglishProductName]


-- QUERY  #5: HOW TO REPORT PRODUCT WISE TOTAL SALES? 
SELECT [EnglishProductName], '$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
GROUP BY [EnglishProductName]


-- TASK 1:  HOW TO REPORT TOTAL SALES OF ALL PRODUCTS IN ADDITION TO ABOVE OUTPUT?
-- TASK 2:  HOW TO REPORT PRODUCT WISE TOTAL SALES IN DESCENDING ORDER AND THEN FINALLY GRAND TOTAL ?


-- QUERY 6: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT CALENDARYEAR, [EnglishProductName],
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY CALENDARYEAR, [EnglishProductName]



-- QUERY 7: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- QUERY 8: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(DATE,[FullDateAlternateKey]) AS SALE_DAY, [EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]

-- TASK 3: USE CAST() INSTEAD OF CONVERT() FOR QUERIES ABOVE



-- QUERY 9: JOINING 3 TABLES
--REQ : HOW TO REPORT LIST OF ALL PRODUCT WISE SALES BASED ON EACH YEAR?
SELECT 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], CONVERT(VARCHAR(30),[FullDateAlternateKey], 104) AS SALE_DAY, [EnglishProductName], 
'$ ' + CONVERT(VARCHAR(10), CONVERT(INT, SUM([SalesAmount]))) AS TOTAL_SALES  
FROM [dbo].[PRODUCTS_DATA]
INNER JOIN
[dbo].[SALES_DATA]
ON
PRODUCTS_DATA.PRODUCTKEY = SALES_DATA.[ProductKey]
INNER JOIN
TIME_DATA 
ON
TIME_DATA.TIMEKEY = SALES_DATA.ORDERDATEKEY
GROUP BY 
CALENDARYEAR,[CalendarQuarter], [EnglishMonthName], [FullDateAlternateKey], [EnglishProductName]


-- TASK 4 : HOW TO REPORT TOTAL SALES OF ALL PRODUCTS WITH MINIMUM LIST PRICE PRODUCTS?
-- TASK 5 : HOW TO REPORT TOTAL SALES OF ALL PRODUCTS EXCEPT MAXIMUM LIST PRICE PRODUCTS?


-- TASK 6 : HOW TO REPORT TOTAL SALES OF ALL PRODUCTS EXCEPT MAXIMUM LIST PRICE PRODUCTS FROM MINIMUM STANDARD COST?


-- WE ARE MEETING AS USUAL. AT 7 30 PM IST. 

