CREATE DATABASE UNIVDATABASE11J

USE UNIVDATABASE11J

-- TABLE 1:
CREATE TABLE COURSES
(
COURSE_ID INT UNIQUE ,  
COURSE_NAME VARCHAR(30) NOT NULL ,  	
COURSE_DUR SMALLINT CHECK (COURSE_DUR = 180 OR COURSE_DUR = 240)
)
	
INSERT COURSES VALUES ( 101, 'COMPUTERS',180), 
					  ( 102, 'CIVIL', 180 ), 
					  ( 103, 'robotics',180)

select * from COURSES

-- SERVER ARCH
-- DATABASE ARCH
-- INDEX ARCH
-- AGENT ARCH
-- PROCESSOR ARCH
-- PAGE ARCH		[GAM, SGAM, .... ]
-- FT ARCH			[FTS ARCH]



-- TABLE 2: 
CREATE TABLE tblStudents
(
StdId	INT		UNIQUE,   
StdName	VARCHAR(30) NOT NULL,
StdAge	TINYINT CHECK ( STDAGE >= 18 ),
StdGender CHAR	CHECK ( STDGENDER IN ( 'M','F' )),
StdCourse_ID INT	REFERENCES COURSES(COURSE_ID)   
)

INSERT INTO tblStudents VALUES ( 100001, 'SAI', 34, 'M', 101 ) 
INSERT INTO tblStudents VALUES ( 100002, 'SAISH', 33, 'M', 101 ) 
INSERT INTO tblStudents VALUES ( 100003, 'JOHN', 34, 'M', 102 ) 
INSERT INTO tblStudents VALUES ( 100004, 'JOHNY', 33, 'M', 102 ) 
INSERT INTO tblStudents VALUES ( 100005, 'AMIN', 34, 'M', 101 ) 
INSERT INTO tblStudents VALUES ( 100006, 'AMINI', 30, 'F', 101 ) 
INSERT INTO tblStudents VALUES ( 100007, 'JENY', 24, 'F', 101 ) 
INSERT INTO tblStudents VALUES ( 100008, 'JON', 30, 'M', 102 ) 

select * from COURSES
select * from tblStudents


-- JOINS	:	 COMPARE, COMBINE

-- REQUIREMENT 1:	HOW TO REPORT LIST OF ALL COURSES AND RESPECTIVE STUDENTS?
			SELECT * FROM  
			COURSES     			-- LEFT   TABLE
			INNER JOIN
			tblStudents				-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID

-- REQUIREMENT 2: HOW TO REPORT LIST OF ALL COURSES WITH & WITHOUT STUDENTS?
			SELECT * FROM  
			COURSES     			-- LEFT   TABLE
			LEFT OUTER JOIN			-- ALL LEFT  + MATCHING RIGHT. NON MATCH RIGHT  = NULL
			tblStudents				-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID


-- REQUIREMENT 3: HOW TO REPORT LIST OF ALL COURSES WITH & WITHOUT STUDENTS?
			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			RIGHT OUTER JOIN	-- ALL RIGHT  + MATCHING LEFT. NON MATCH LEFT  = NULL
			COURSES 			-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID

-- REQUIREMENT 4: HOW TO REPORT LIST OF ALL COURSES WITH & WITHOUT STUDENTS EXCEPT CIVIL COURSE?
			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			RIGHT OUTER JOIN		-- ALL RIGHT  + MATCHING LEFT. NON MATCH LEFT  = NULL
			COURSES 			-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID
			WHERE COURSES.COURSE_NAME != 'CIVIL'


-- REQUIREMENT 5:	HOW TO REPORT LIST OF ALL COURSES WITH & WITHOUT STUDENTS?
--					HOW TO REPORT LIST OF ALL STUDENTS  WITH & WITHOUT COURSES ?
			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			FULL OUTER JOIN		
			COURSES 			-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID
		

-- REQUIREMENT 6: HOW TO REPORT ALL POSSIBLE COMBINATIONS FOR COURSES AND STUDENTS?
-- MEANS, WE NEED TO JOIN THE TABLES WITHOUT ANY COMPARISIONS.
			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			CROSS JOIN	
			COURSES 			-- RIGHT  TABLE


			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			CROSS APPLY	
			COURSES 			-- RIGHT  TABLE


-- MERGE JOIN :  THIS OPTION IS USED FOR INNER & OUTER JOINS. TO ENSURE FASTER JOIN QUERY EXECUTION FOR BIG TABLES
-- LOOP JOIN :  THIS OPTION IS USED FOR INNER & OUTER JOINS. TO ENSURE FASTER JOIN QUERY EXECUTION FOR SMALLER TABLES
-- HASH JOIN :  THIS OPTION IS USED FOR INNER & OUTER JOINS. TO ENSURE FASTER JOIN QUERY EXECUTION FOR HEAP TABLES

-- THRESHOLD VALUE FOR TABLE SIZE :  10 GB
-- HEAP : SUCH TABLES WITHOUT ANY INDEXES

-- EXAMPLE FOR MERGE JOIN
-- REQUIREMENT 1:	HOW TO REPORT LIST OF ALL COURSES AND RESPECTIVE STUDENTS?
			SELECT * FROM  
			COURSES     			-- LEFT   TABLE
			INNER MERGE JOIN
			tblStudents				-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID

-- EXAMPLE FOR LOOP JOIN
-- REQUIREMENT 1:	HOW TO REPORT LIST OF ALL COURSES AND RESPECTIVE STUDENTS?
			SELECT * FROM  
			COURSES     			-- LEFT   TABLE
			INNER LOOP JOIN
			tblStudents				-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID

-- EXAMPLE FOR HASH JOIN
-- REQUIREMENT 1:	HOW TO REPORT LIST OF ALL COURSES AND RESPECTIVE STUDENTS?
			SELECT * FROM  
			COURSES     			-- LEFT   TABLE
			INNER HASH JOIN
			tblStudents				-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID


-- Q1.	 IN WHICH CASES, YOU SEE THE DATA IS AUTO SORTED WITHOUT USING ORDER BY?

-- Q2.	 HOW TO REPORT LIST OF ALL COURSES WITHOUT ANY STUDENT?
		 -- REFERENCE QUERY BELOW
			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			RIGHT OUTER JOIN		-- ALL RIGHT  + MATCHING LEFT. NON MATCH LEFT  = NULL
			COURSES 			-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID
			WHERE COURSES.COURSE_NAME != 'CIVIL'

-- Q3.	 HOW TO FINE TUNE THE ABOVE QUERY? MEANS, HOW TO MAKE IT EXECUTE OR RUN FASTER?




