-- Q1.	 IN WHICH CASES, YOU SEE THE DATA IS AUTO SORTED WITHOUT USING ORDER BY?
UNION ALL
DISTINCT
MERGE OPTION IN INNER JOIN & OUTER JOIN

-- Q2.	 HOW TO REPORT LIST OF ALL COURSES WITHOUT ANY STUDENT?
		 -- REFERENCE QUERY BELOW
			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			RIGHT OUTER JOIN	-- ALL RIGHT  + MATCHING LEFT. NON MATCH LEFT  = NULL
			COURSES 			-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID
			WHERE COURSES.COURSE_NAME != 'CIVIL'


			SELECT * FROM  
			tblStudents	     	-- LEFT   TABLE
			RIGHT OUTER JOIN	-- ALL RIGHT  + MATCHING LEFT. NON MATCH LEFT  = NULL
			COURSES 			-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID
			WHERE tblStudents.StdCourse_ID  IS NULL 

-- Q3.	 HOW TO FINE TUNE THE ABOVE QUERY? MEANS, HOW TO MAKE IT EXECUTE OR RUN FASTER?

			1. DEFINE INDEXES ON StdCourse_ID
			2. USE MERGE OR LOOP OR HASH JOIN :
			SELECT * FROM  
			tblStudents	     		-- LEFT   TABLE
			RIGHT OUTER MERGE JOIN	-- ALL RIGHT  + MATCHING LEFT. NON MATCH LEFT  = NULL
			COURSES 				-- RIGHT  TABLE
			ON 
			tblStudents.StdCourse_ID = COURSES.COURSE_ID
			WHERE tblStudents.StdCourse_ID  IS NULL 


