
-- QUERY 1: HOW TO CREATE NEW DATABASE?   
CREATE   DATABASE 	EMPLOYEE_DB				

-- QUERY 2: HOW TO CONNECT TO ABOVE DATABASE? 
USE  EMPLOYEE_DB					

-- QUERY 3: HOW TO CREATE NEW TABLE IN ABOVE DATABASE?	WORKS ON ANY SERVER
CREATE TABLE EMPLOYEE_INFO			
 (
	EMP_ID  INT,				-- this column stores DIGITS IN CRORES. 
    EMP_FNAME VARCHAR (30),		-- this column stores upto 30 CHARACTERS 
	EMP_LNAME VARCHAR (40),		-- this column stores upto 40 CHARACTERS 
	EMP_CNTRY CHAR(40),			-- this column stores upto 40 CHARACTERS 
	EMP_SAL  BIGINT				-- this column stores DIGITS IN TRILLIONS. 
)

-- QUERY 4:
INSERT INTO  EMPLOYEE_INFO VALUES (1001, 'AMIN', 'A', 'CANADA', 45678)	  

-- QUERY 5:
INSERT   EMPLOYEE_INFO VALUES 	('1002', 'JOHN', 'A', 'CANADA', 643643)

-- QUERY 6: WHAT IF WE DONT KNOW THE VALUE OF A COLUMN?
INSERT   EMPLOYEE_INFO VALUES (1003, 'AMIN', 'H', 'USA', NULL)   

-- QUERY 7: EXAMPLE FOR A BATCH?		
INSERT   EMPLOYEE_INFO VALUES (1004, 'AMINI', 'L', 'USA', 36363)			
INSERT   EMPLOYEE_INFO VALUES (1000, 'TEST', ' ', 'INDIA', 45745)
INSERT   EMPLOYEE_INFO VALUES (1005, 'TEST2', ' ', 'INDIA', NULL), (1006, 'TEST2', ' ', 'INDIA', NULL)


-- QUERY 8: HOW TO REPORT / VERIFY ABOVE INSERTED DATA IN THE TABLE ?
SELECT EMP_ID, EMP_LNAME, EMP_CNTRY, EMP_SAL, EMP_FNAME FROM EMPLOYEE_INFO

-- QUERY 9: HOW TO REPORT / VERIFY ABOVE INSERTED DATA IN THE TABLE? 
SELECT * FROM EMPLOYEE_INFO

-- QUERY 10: HOW TO REPORT ALL EMPLOYEES WITH SALARY VALUE ABOVE 60K?
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_SAL >= 60000

-- QUERY 11: HOW TO REPORT ALL EMPLOYEES FROM INDIA OR CANADA?
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'INDIA'  OR  EMP_CNTRY = 'CANADA'


-- QUERY 12: HOW TO REPORT ALL EMPLOYEES FROM INDIA OR CANADA? 
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY IN  ( 'INDIA' , 'CANADA' )

-- QUERY 13: HOW TO REPORT ALL EMPLOYEES EXCEPT FROM INDIA OR CANADA? 
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY NOT IN  ( 'INDIA' , 'CANADA' )


-- QUERY 14: HOW TO REPORT ALL EMPLOYEES WITH SALARY BETWEEN 30000 AND 60000?
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_SAL BETWEEN 30000 AND 60000

-- QUERY 15: HOW TO REPORT ALL EMPLOYEES WITH SALARY NOT BETWEEN 30000 AND 60000?
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_SAL NOT BETWEEN 30000 AND 60000


-- QUERY 16: HOW TO REPORT ALL EMPLOYEES WHOSE SALARY IS UNKNOWN?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_SAL IS NULL

-- QUERY 17: HOW TO REPORT ALL EMPLOYEES WHOSE SALARY IS KNOWN?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_SAL IS NOT NULL


-- QUERY 18: HOW TO REPORT ALL EMPLOYEES WHOSE FIRST NAME IS 'AMIN'?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_FNAME = 'AMIN'

-- QUERY 19: HOW TO REPORT ALL EMPLOYEES WHOSE FIRST NAME STARTS WITH LETTER 'A'?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_FNAME LIKE 'A%'   

-- QUERY 20: HOW TO REPORT ALL EMPLOYEES WHOSE FIRST NAME DOES NOT END WITH 'N'?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_FNAME NOT LIKE '%N'

-- QUERY 21: HOW TO REPORT ALL EMPLOYEES WHOSE FIRST NAME STARTS WITH A, ENDS WITH N AND TOTAL OF 4 CHARACTERS?
 SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_FNAME LIKE 'A__N'	-- SPECIFY 2 UNDERSCORES

 -- % MEANS TO REPORT ANY NUMBER OF CHARACTERS
 -- _ MEANS TO REPORT ONE CHARACTER







-- QUERY 22: HOW TO REPORT ALL EMPLOYEES FROM CANADA, THEN EMPLOYEES FROM INDIA?
  SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'CANADA' 
  SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'INDIA' 

SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'CANADA' 
UNION ALL			-- USED TO COMBINE RESULTS FROM MULTIPLE QUERIES. RESULT (OUTPUT) IN ORDER.
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'INDIA' 


SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'CANADA' 
UNION				-- USED TO COMBINE RESULTS FROM MULTIPLE QUERIES. RESULT (OUTPUT) MAY NOT BE IN ORDER.
SELECT  *  FROM EMPLOYEE_INFO WHERE EMP_CNTRY = 'INDIA' 



-- QUERY 23 : HOW TO REPORT ALL EMPLOYEES WITH ASCENDING ORDER OF SALARIES? 
SELECT  *  FROM EMPLOYEE_INFO ORDER BY EMP_SAL ASC

-- QUERY 24: HOW TO REPORT ALL EMPLOYEES WITH DESCENDING ORDER OF SALARIES? 
SELECT  *  FROM EMPLOYEE_INFO ORDER BY EMP_SAL DESC

-- QUERY 25 : HOW TO REPORT TOP 3 EMPLOYEES WITH HIGHEST SALARY ?
SELECT  TOP 3 *  FROM EMPLOYEE_INFO ORDER BY EMP_SAL asc

-- QUERY 26 : HOW TO REPORT 3RD AND REMAINING EMPLOYEES ? 
 SELECT * FROM EMPLOYEE_INFO ORDER BY EMP_ID asc OFFSET 2 ROWS		

-- QUERY 27 : HOW TO REPORT MAXIMUM SALARY OUT OF (FOR) ALL EMPLOYEES ? 
SELECT  EMP_SAL  FROM EMPLOYEE_INFO						-- TO REPORT ALL VALUES OF A COLUMN

SELECT  distinct EMP_SAL  FROM EMPLOYEE_INFO			-- TO REPORT UNIQUE VALUES OF A COLUMN

SELECT MAX( EMP_SAL ) FROM EMPLOYEE_INFO

SELECT MAX( EMP_SAL ) AS  MAXIMUM_SALARY FROM EMPLOYEE_INFO		-- AS MEANS "ALIASING". A TEMPORARY NAME TO A COLUMN

-- QUERY 28: HOW TO REPORT LIST OF ALL EMPLOYEES WITH MAXIMUM SALARY? 
SELECT  * FROM EMPLOYEE_INFO WHERE EMP_SAL  =  ( SELECT MAX ( EMP_SAL ) FROM EMPLOYEE_INFO )  -- A SUB QUERY



-- QUERY 29:  HOW TO FIND THE LIST OF ALL EMPLOYEES WITH UNKNOWN SALARY VALUES AND REPLACE SUCH SALARY VALUES WITH 10000 ?
UPDATE EMPLOYEE_INFO SET EMP_SAL  = 10000 WHERE EMP_SAL IS NULL
SELECT * FROM EMPLOYEE_INFO

-- QUERY 30:   HOW TO FIND THE LIST OF ALL EMPLOYEES WITH 10000 SALARY VALUE AND DELETE OR REMOVE SUCH EMPLOYEES FROM THE TABLE?
DELETE FROM EMPLOYEE_INFO WHERE EMP_SAL = 10000					-- DELETE STATEMENT IS OPPOSITE OF INSERT
SELECT * FROM EMPLOYEE_INFO

DELETE FROM EMPLOYEE_INFO										-- NO CONDITION. HENCE, COMPELTE TABLE DATA IS DELETED [REMOVED]			
SELECT * FROM EMPLOYEE_INFO										-- TABLE IS EMPTY

TRUNCATE TABLE EMPLOYEE_INFO									-- NO CONDITION. HENCE, COMPELTE TABLE DATA IS DELETED [REMOVED]
SELECT * FROM EMPLOYEE_INFO										-- TABLE IS EMPTY


-- QUERY 31:   HOW TO ADD NEW COLUMN TO EXISTING TABLE?
ALTER TABLE EMPLOYEE_INFO ADD EMP_LOCATION VARCHAR(30)
SELECT * FROM EMPLOYEE_INFO

-- QUERY 32:	HOW TO MODIFY THE STRUCTURE OF EXISING COLUMN IN THE EXISTING TABLE?
ALTER TABLE EMPLOYEE_INFO ALTER COLUMN EMP_LOCATION VARCHAR(3000)

-- QUERY 33: HOW TO REMOVE AN EXISING COLUMN FROM THE EXISTING TABLE?
ALTER TABLE EMPLOYEE_INFO DROP COLUMN EMP_LOCATION 

-- QUERY 34: HOW TO REMOVE THE TABLE FROM DATABASE?
DROP TABLE EMPLOYEE_INFO

-- QUERY 35: HOW TO REMOVE THE DATABASE FROM THE SERVER (INSTANCE)?
USE MASTER 
GO
DROP DATABASE EMPLOYEE_DB	


/*
<				>
=				!=
OR				AND
IN				NOT IN
BETWEEN			NOT BETWEEN
IS				IS NOT
LIKE			NOT LIKE
UNION			UNION ALL
TOP				OFFSET
ASC				DESC

CREATE			DROP
INSERT			DELETE  or TRUNCATE

CHAR			VARCHAR
BATCH		&	GO
*/

