use tempdb 
go

CREATE TABLE tblPopulation		
(
Country VARCHAR(100),
[State] VARCHAR(100),
City VARCHAR(100),
Population INT
)

INSERT tblPopulation VALUES('COUNTRY1', 'STATE1','CITY1',9 ),	('COUNTRY1', 'STATE1','CITY2',8 )
INSERT tblPopulation VALUES('COUNTRY1', 'STATE2','CITY1',5.5), ('COUNTRY1', 'STATE2','CITY2',7.5)
INSERT tblPopulation VALUES('COUNTRY2', 'STATE1','CITY1',9.5),	('COUNTRY2', 'STATE1','CITY2',2.5)
INSERT tblPopulation VALUES('COUNTRY2', 'STATE2','CITY1',1.5),	('COUNTRY3', 'STATE1','CITY1',30)
INSERT tblPopulation VALUES('COUNTRY3', 'STATE1','CITY2',20)

INSERT tblPopulation VALUES(NULL, 'STATE1','CITY2',120)


-- QUERY 1: HOW TO REPORT LIST OF ALL POPULATION DETAILS?
SELECT * FROM tblPopulation

-- QUERY 2: HOW TO REPORT LIST OF ALL COUNTRY NAMES ONLY?
SELECT Country FROM tblPopulation

-- QUERY 3: HOW TO REPORT LIST OF UNIQUE COUNTRY NAMES?
SELECT DISTINCT Country FROM tblPopulation

-- QUERY 4: HOW TO REPORT LIST OF UNIQUE COUNTRY NAMES?
SELECT Country FROM tblPopulation
GROUP BY Country

-- TILL NOW,   DISTINCT ALTERNATIVE   IS "GROUP BY"
-- THEN WHAT IS THE ACTUAL DIFFERENCE BETWEEN DISTINCT AND GROUP BY? MEANS, WHEN TO USE WHICH ??

-- QUERY 5:  HOW TO REPORT TOTAL POPULATION FOR ALL COUNTRIES?
SELECT SUM(Population) AS TOTAL_POPULATION FROM tblPopulation

-- QUERY 6:
--- LETS COMBINE BOTH QUERY #4 AND QUERY #5.
-- MEANS, QUERY TO REPORT COUNTRY WISE TOTAL POPULATION?
-- FOR THIS, WE NEED TO REPORT EACH (UNIQUE) COUNTRY AND ALSO SUM OF POPULATION (AGGREGATION) FOR EACH COUNTRY
SELECT Country, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY Country

-- QUERY 7: HOW TO REPORT COUNTRY WISE, STATE WISE TOTAL POPULATION?
SELECT Country, STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY Country, State

-- RULE : WHENEVER A QUERY CONTAINS GROUP BY THEN COLUMNS USED IN GROUP BY SHOULD BE USED IN SELECT ALSO. 
SELECT Country, STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY Country				-- ERROR. REASON :  STATE COLUMN IS NOT INCLUDED IN GROUP BY BUT INCLUDED IN SELECT


-- QUERY 8 : HOW TO SPECIFY CONDITIONS ON AGGREGATED DATA?
SELECT Country, STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY Country, State
HAVING SUM(Population) > 15


-- QUERY 9 : HOW TO SPECIFY CONDITIONS ON AGGREGATED DATA AND NON AGGREGATED DATA?
SELECT Country, STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
WHERE STATE = 'STATE1'				-- CONDITIONS ON NON-AGGREGATED DATA. BEFORE GROUP BY
GROUP BY Country, State				-- CONDITIONS ON AGGREGATED DATA. AFTER GROUP BY
HAVING SUM(Population) > 0


-- QUERY 10 : HOW TO REPORT COUNTRY WISE TOTAL POPULATION & GRAND TOTAL POPULATION?
SELECT Country, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY Country

SELECT Country, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(Country)


-- QUERY 11 : HOW TO REPORT COUNTRY WISE TOTAL POPULATION & GRAND TOTAL POPULATION?
SELECT ISNULL(Country, 'GRAND TOTAL'), SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(Country)

SELECT ISNULL(Country, 'GRAND TOTAL') AS  COUNTRY, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(Country)

SELECT COALESCE(Country, 'GRAND TOTAL') AS  COUNTRY, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(Country)

SELECT Country,STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(Country, STATE)		-- COUNTRY WISE TOTALS + COUNTRY WISE STATE WISE TOTALS + GRAND TOTAL
	
SELECT Country,STATE, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY CUBE (Country, STATE)		-- COUNTRY WISE TOTALS + STATE WISE TOTALS + COUNTRY WISE STATE WISE TOTALS + GRAND TOTAL



-- QUERY 12: HOW TO IDENTIFY NEW ROWS RESULTED FROM ROLLUP AND CUBE?
-- SOLUTION : "GROUPING"
SELECT Country, SUM(Population) AS TOTAL_POPULATION FROM tblPopulation
GROUP BY ROLLUP(Country)

SELECT Country, SUM(Population) AS TOTAL_POPULATION, GROUPING(Country) FROM tblPopulation
GROUP BY ROLLUP(Country)

SELECT Country, STATE, SUM(Population) AS TOTAL_POPULATION, GROUPING(Country), GROUPING (STATE) FROM tblPopulation
GROUP BY ROLLUP(Country, STATE)


-- TASK 1:	HOW TO REPORT ALL SOURCE DATA FIRST. THEN SUB TOTALS NEXT AND THEN GRAND TOTAL LAST FROM ABOVE QUERY?

-- TASK 2:	HOW TO REPORT ONLY SUB TOTALS AND THEN GRAND TOTAL FROM ABOVE QUERY?

-- TASK 3:	HOW TO REPORT STATE WISE CITY WISE TOTAL POPULATION FOR ALL COUNTRIES?

-- TASK 4:	HOW TO REPORT STATE WISE CITY WISE TOTAL POPULATION FOR ALL COUNTRIES EXCEPT FOR COUNTRY 1 OR EXCEPT FOR TOTAL POPULATION BELOW 10m?






