-- EXAMPLE 2:  USER DEFINED FUNCTIONS 
CREATE FUNCTION FN_REPORT_EMPLOYEES (@Country varchar(30))
RETURNS table
AS
RETURN ( SELECT * FROM EMPLOYEE_INFO WHERE EMP_CNTRY = @Country)

-- TO ACCESS ABOVE FUNCTION
SELECT * FROM FN_REPORT_EMPLOYEES('INDIA')-- EXAMPLE 1:  USER DEFINED VIEWS 

-- IMPORTANT SYSTEM FUNCTIONS : FOR METADATA [SYSTEM INFORMATION] AUDITS
SELECT DB_NAME()		-- REPORTS CURRENTLY CONNECTED DATABASE NAME
SELECT DB_ID()			-- REPORTS CURRENTLY CONNECTED DATABASE ID

SELECT DB_NAME(6)					-- REPORTS CURRENTLY CONNECTED DATABASE NAME FOR A GIVEN DATABASE ID
SELECT DB_ID('AUDIT_DATABASE')		-- REPORTS CURRENTLY CONNECTED DATABASE ID FOR A GIVEN DATABASE NAME

SELECT OBJECT_ID('EMPLOYEE_INFO')
SELECT OBJECT_NAME(581577110)

SELECT GETDATE()		-- REPORTS TODAY'S DATE & TIME
SELECT NEWID()			-- REPORTS A UNIQUE IDENTIFIER = GUID = GLOBALLY UNIQUE IDENTIFIER

SELECT @@SERVERNAME		-- REPORTS THE CURRENTLY CONNECTED SERVER NAME
SELECT @@VERSION		-- REPORTS VERSION AND EDITION DETAILS OF THE CURRENTLY CONNECTED SERVER

