-- EXAMPLE 3:  USER DEFINED PROCEDURES 
CREATE PROCEDURE SP_REPORT_EMPLOYEES (@Country varchar(30))
AS
SELECT * FROM EMPLOYEE_INFO	WHERE EMP_CNTRY = @Country

-- TO ACCESS ABOVE STORED PROCEDURE
EXEC SP_REPORT_EMPLOYEES 'INDIA'
EXEC SP_REPORT_EMPLOYEES 'USA'


-- IMPORTANT SYSTEM PROCEDURES : FOR METADATA [SYSTEM INFORMATION] AUDITS
EXEC SP_HELPDB		-- TO REPORT LIST OF ALL DATABASES IN THE SERVER
EXEC SP_HELP		-- TO REPORT LIST OF ALL OBJECTS [TABLES, VIEWS, KEYS, INDEXES....] IN THE DATABASE
EXEC SP_HELP'EMPLOYEE_INFO'			-- TO REPORT DEFINITION OF THE GIVEN OBJECT [TABLE]
EXEC SP_HELPINDEX 'EMPLOYEE_INFO'	-- TO REPORT ALL INDEXES OF THE GIVEN TABLE
EXEC SP_PKEYS	'EMPLOYEE_INFO'		-- TO REPORT PRIMARY KEY INFORMATION OF THE GIVEN TABLE
EXEC SP_DEPENDS	'EMPLOYEE_INFO'		-- TO REPORT ALL DEPENDANCIES ON THE GIVEN TABLE
EXEC SP_RENAME		'EMPLOYEE_INFO', 'NEW_TABLE_NAME'		-- TO REPORT ALL DEPENDANCIES ON THE GIVEN TABLE
EXEC SP_RECOMPILE	'SP_REPORT_EMPLOYEES'	-- TO RECOMPILE THE QUERY INSIDE A PROICEDURE / VIEW / FUNCTION. FOR FASTER EXECUTION
EXEC SP_WHO2						-- REPORTS ALL CURRENT CONNECTIONS TO SQL SERVER