CREATE DATABASE AUDIT_DATABASE 
GO
USE AUDIT_DATABASE
GO

CREATE TABLE EMPLOYEE_INFO			
(
EMP_ID		INT,				-- this column stores DIGITS (NUMBERS) IN CRORES. SIZE  = 4 BYTES PER VALUE.
EMP_FNAME	VARCHAR (30),		-- this column stores upto 30 CHARACTERS. TO STORE VARYING or CHANGING DATA.   
EMP_LNAME	VARCHAR (40),		-- this column stores upto 40 CHARACTERS. TO STORE VARYING or CHANGING DATA. 
EMP_CNTRY	CHAR(50),			-- this column stores upto 50 CHARACTERS. TO STORE FIXED DATA. EX: EMPLOYEE GENDER   
EMP_SAL		BIGINT				-- this column stores DIGITS (NUMBERS) IN TRILLIONS.   SIZE  = 8 BYTES PER VALUE.
)						

INSERT INTO  EMPLOYEE_INFO VALUES (1001, 'AMIN', 'A', 'CANADA', 45678) 
INSERT   EMPLOYEE_INFO VALUES	('1002', 'JOHN', 'A', 'CANADA', 643643)			
INSERT   EMPLOYEE_INFO VALUES	(1003, 'SAI', 'H', 'INDIA', 36363)			
INSERT   EMPLOYEE_INFO VALUES	(1004, 'SAISHA', 'T', 'INDIA', 0)			
INSERT   EMPLOYEE_INFO VALUES	(1005, 'SAISH', 'G', 'INDIA', 43643)
INSERT   EMPLOYEE_INFO VALUES (1006, 'ADAM', 'H', 'USA', NULL)   
INSERT   EMPLOYEE_INFO VALUES (1007, 'AMINI', 'L', 'INDIA', 36363)			
INSERT   EMPLOYEE_INFO VALUES (1000, 'TEST', ' ', 'INDIA', NULL)
INSERT   EMPLOYEE_INFO VALUES (1008, 'TEST2', ' ', 'INDIA', NULL)
INSERT   EMPLOYEE_INFO VALUES (1000, 'TEST', ' ', 'INDIA', NULL)


SELECT * FROM EMPLOYEE_INFO	
WHERE EMP_CNTRY = 'INDIA'


-- EXAMPLE 1:  USER DEFINED VIEWS 
CREATE VIEW VW_INDIA_EMPLOYEES
AS
SELECT * FROM EMPLOYEE_INFO	
WHERE EMP_CNTRY = 'INDIA'

-- TO ACCESS ABOVE VIEW
SELECT * FROM VW_INDIA_EMPLOYEES

-- WE CAN PERFORM DML OPERATIONS ON THIS VIEW. SUCH OPERATIONS WILL ACTUALLY IMPACT THE BASE TABLE.
-- REASON : VIEW DOES NOT STORE ANY DATA. VIEW STORE ONLY QUERY.
INSERT INTO VW_INDIA_EMPLOYEES VALUES (2001, 'SAI', 'PHANI', 'INDIA', NULL) 
SELECT * FROM EMPLOYEE_INFO	

-- IMPORTANT SYSTEM VIEWS : FOR METADATA [SYSTEM INFORMATION] AUDITS
SELECT * FROM SYS.DATABASES		-- TO REPORT LIST OF ALL DATABASES IN THE SERVER
SELECT * FROM SYS.SCHEMAS		-- TO REPORT LIST OF ALL SCHEMAS IN THE DATABASE
SELECT * FROM SYS.TABLES		-- TO REPORT LIST OF ALL TABLES IN THE DATABASE
SELECT * FROM SYS.INDEXES		-- TO REPORT LIST OF ALL INDEXES IN THE DATABASE
SELECT * FROM SYS.OBJECTS		-- TO REPORT LIST OF ALL OBJECTS [TABLES, VIEWS, KEYS, INDEXES....] IN THE DATABASE
